In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [ ]:
Names=['Rames','Suresh','Satish','Mahesh']
Age=[20,22,24,26]

**Step-1 :Create a Dataframe**

In [ ]:
pd.DataFrame(Names)
pd.DataFrame(Names,'Names') #Names assume as index
pd.DataFrame(Names,columns='Names') # Columns Array
pd.DataFrame(Names,columns=['Names'])

In [8]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
pd.DataFrame(Names,'Names')

TypeError: Index(...) must be called with a collection of some kind, 'Names' was passed

In [4]:
pd.DataFrame(Names,columns='Names')

TypeError: Index(...) must be called with a collection of some kind, 'Names' was passed

In [10]:
pd.DataFrame(Names,columns=['Names'])

    Names
0  Ramesh
1  Suresh
2  Satish
3  Mahesh

In [11]:
pd.DataFrame(Names,columns=['Names'])
pd.DataFrame(Names,
             index=['A','B','C','D'],
             columns=['Names'])

    Names
A  Ramesh
B  Suresh
C  Satish
D  Mahesh

In [13]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
DATA=[Names,Age]
pd.DataFrame(DATA).T

        0   1
0  Ramesh  20
1  Suresh  22
2  Satish  24
3  Mahesh  26

In [17]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
DATA=zip(Names,Age)
pd.DataFrame(DATA,index=['A','B','C','D'],columns=['Names','Age'])

    Names  Age
A  Ramesh   20
B  Suresh   22
C  Satish   24
D  Mahesh   26

**Step-2 : Add a new column to already existed dataframe**

In [ ]:
df[cols_name]

In [18]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
DATA=zip(Names,Age)
df=pd.DataFrame(DATA,columns=['Names','Age'])

In [19]:
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24
3  Mahesh   26

In [20]:
df['Names']  #Selection

0    Ramesh
1    Suresh
2    Satish
3    Mahesh
Name: Names, dtype: object

In [21]:
df['Age']=[30,32,34,36] #Update

In [22]:
df

    Names  Age
0  Ramesh   30
1  Suresh   32
2  Satish   34
3  Mahesh   36

In [23]:
df['City']=['hyd','blr','pune','vja']  #Creation

In [24]:
df

    Names  Age  City
0  Ramesh   30   hyd
1  Suresh   32   blr
2  Satish   34  pune
3  Mahesh   36   vja

**step-4: Create a Dataframe using dictonary**

In [4]:
import pandas as pd
d={'Names':['Kiran','Teja','Mani','Satya','Vardhan'],
   'Age':[24,23,20,22,20],
   'City':['Vja','Hyd','Skm','Vzg','Gun']}
df=pd.DataFrame(d)
df

     Names  Age City
0    Kiran   24  Vja
1     Teja   23  Hyd
2     Mani   20  Skm
3    Satya   22  Vzg
4  Vardhan   20  Gun

In [6]:
d={'Names':'Kiran',
   'Age':'24',
   'City':'Vja'}
pd.DataFrame(d,index=[1])

   Names Age City
1  Kiran  24  Vja

**Step-5: Drop a new column**

In [ ]:
 df.drop(labels,axis=0,index,columns,inplace=True)

In [9]:
df.drop('City')

KeyError: "['City'] not found in axis"

In [10]:
df.drop('City',axis=1)

     Names  Age
0    Kiran   24
1     Teja   23
2     Mani   20
3    Satya   22
4  Vardhan   20

In [12]:
df.drop(columns=['City'])

     Names  Age
0    Kiran   24
1     Teja   23
2     Mani   20
3    Satya   22
4  Vardhan   20

In [13]:
df.drop(2)

     Names  Age City
0    Kiran   24  Vja
1     Teja   23  Hyd
3    Satya   22  Vzg
4  Vardhan   20  Gun

In [14]:
df.drop(2,axis=1)

KeyError: '[2] not found in axis'

In [15]:
df.drop(2,axis=0)

     Names  Age City
0    Kiran   24  Vja
1     Teja   23  Hyd
3    Satya   22  Vzg
4  Vardhan   20  Gun

In [16]:
df.drop(index=[2])

     Names  Age City
0    Kiran   24  Vja
1     Teja   23  Hyd
3    Satya   22  Vzg
4  Vardhan   20  Gun

In [17]:
df
# here the inplace=false because of the data cannot drop on column in table then we can use 
#inplace = True then the data will drop on column in table

     Names  Age City
0    Kiran   24  Vja
1     Teja   23  Hyd
2     Mani   20  Skm
3    Satya   22  Vzg
4  Vardhan   20  Gun

In [18]:
df.drop('City',axis=1,inplace=True)

In [19]:
df

     Names  Age
0    Kiran   24
1     Teja   23
2     Mani   20
3    Satya   22
4  Vardhan   20

**Step-6: Rename**

In [31]:
df.rename(index={0:8},inplace=True)
df

     Names  Age
8    Kiran   24
1     Teja   23
2     Mani   20
3    Satya   22
4  Vardhan   20

In [32]:
df

     Names  Age
8    Kiran   24
1     Teja   23
2     Mani   20
3    Satya   22
4  Vardhan   20

**step-7 Save the Dataframe**

- .csv
- .xlsx
- where you want to save : dictonary
- on what name you want save : name of the file
- on what extension you want to save : .csv ,,xlsx
- different locations : "C:\Users\jupud_zwpuydo\FSDS\EDA\Pandas.ipynb"
- "C:\Users\jupud_zwpuydo\FSDS\EDA\Pandas.ipynb\df1.xlsx"
- "C:\Users\jupud_zwpuydo\FSDS\EDA\Pandas.ipynb\df1.csv"
- same location no need to provide directory : 'df1.csv'

In [35]:
df.to_excel(r"C:\Users\jupud_zwpuydo\FSDS\EDA\df1.xlsx",index=False)
df.to_excel('df1.xlsx',index=False)

In [36]:
pd.read_excel(r"C:\Users\jupud_zwpuydo\FSDS\EDA\df1.xlsx")

     Names  Age
0    Kiran   24
1     Teja   23
2     Mani   20
3    Satya   22
4  Vardhan   20