**How to create a null values in a Data**
- None
- Np.nan

In [1]:
import pandas as pd
import numpy as np

In [2]:
d={'Names':['Kiran','Mani',None,'Satya','teja','Vardhan'],
   'Age':[None,24,22,20,22,23],
   'city':['vjd','blr','vzg','pune',None,'Goa']}
df1=pd.DataFrame(d)
df1

     Names   Age  city
0    Kiran   NaN   vjd
1     Mani  24.0   blr
2     None  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0  None
5  Vardhan  23.0   Goa

In [4]:
d={'Names':['Kiran','Mani',np.nan,'Satya','teja','Vardhan'],
   'Age':[np.nan,24,22,20,22,23],
   'city':['vjd','blr','vzg','pune',np.nan,'Goa']}
df2=pd.DataFrame(d)
df2.to_csv('data2.csv',index=False)

In [5]:
np.nan+10

nan

In [6]:
df1.isnull()
#isnull=wherever Null value there it display as True

   Names    Age   city
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False  False
4  False  False   True
5  False  False  False

In [7]:
df1.isnull().sum()

Names    1
Age      1
city     1
dtype: int64

In [8]:
df1.values

array([['Kiran', nan, 'vjd'],
       ['Mani', 24.0, 'blr'],
       [None, 22.0, 'vzg'],
       ['Satya', 20.0, 'pune'],
       ['teja', 22.0, None],
       ['Vardhan', 23.0, 'Goa']], dtype=object)

In [9]:
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

Names    1
Age      1
city     1
dtype: int64

**Fill the values**

In [10]:

#random fill
df1.fillna(25)

     Names   Age  city
0    Kiran  25.0   vjd
1     Mani  24.0   blr
2       25  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0    25
5  Vardhan  23.0   Goa

In [11]:
#select one columns and wil with value
df1['city'].fillna('Delhi')

0      vjd
1      blr
2      vzg
3     pune
4    Delhi
5      Goa
Name: city, dtype: object

In [12]:
#pad,bfill,backfill,ffill
df1.fillna(method='pad')

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\3887010614.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

     Names   Age  city
0    Kiran   NaN   vjd
1     Mani  24.0   blr
2     Mani  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0  pune
5  Vardhan  23.0   Goa

In [13]:
df1.fillna(method='pad',axis=1)

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

     Names    Age  city
0    Kiran  Kiran   vjd
1     Mani   24.0   blr
2     None   22.0   vzg
3    Satya   20.0  pune
4     teja   22.0  22.0
5  Vardhan   23.0   Goa

In [14]:
df1.fillna(method='bfill')

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

     Names   Age  city
0    Kiran  24.0   vjd
1     Mani  24.0   blr
2    Satya  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0   Goa
5  Vardhan  23.0   Goa

In [15]:
df1.fillna(method='bfill',axis=1)

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

     Names   Age  city
0    Kiran   vjd   vjd
1     Mani  24.0   blr
2     22.0  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0  None
5  Vardhan  23.0   Goa

In [16]:
df1.fillna(method='backfill',axis=1)

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\194193199.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='backfill',axis=1)

     Names   Age  city
0    Kiran   vjd   vjd
1     Mani  24.0   blr
2     22.0  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0  None
5  Vardhan  23.0   Goa

In [17]:
df1.fillna(method='backfill')

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\2955370104.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='backfill')

     Names   Age  city
0    Kiran  24.0   vjd
1     Mani  24.0   blr
2    Satya  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0   Goa
5  Vardhan  23.0   Goa

In [18]:
df1.fillna(method='ffill',axis=1)

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\209249745.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill',axis=1)

     Names    Age  city
0    Kiran  Kiran   vjd
1     Mani   24.0   blr
2     None   22.0   vzg
3    Satya   20.0  pune
4     teja   22.0  22.0
5  Vardhan   23.0   Goa

In [19]:
df1.fillna(method='ffill')

C:\Users\jupud_zwpuydo\AppData\Local\Temp\ipykernel_11008\598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

     Names   Age  city
0    Kiran   NaN   vjd
1     Mani  24.0   blr
2     Mani  22.0   vzg
3    Satya  20.0  pune
4     teja  22.0  pune
5  Vardhan  23.0   Goa

- mean
- median
- mode

In [21]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    22.2
1    24.0
2    22.0
3    20.0
4    22.0
5    23.0
Name: Age, dtype: float64

In [22]:
age_median=df1['Age'].median()
df1['Age'].fillna(age_median)

0    22.0
1    24.0
2    22.0
3    20.0
4    22.0
5    23.0
Name: Age, dtype: float64

**Situation-1**

In [ ]:
 # There is no particular rule howto filling the missing values
# It is completely based on situation

In [24]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [25]:
d1
# I Want to Handover this data to my students with not encode

   Gender
0    Male
1  Female
2    None

In [26]:
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

In [27]:
# The students think that i want to fill  a missing
# data is numericaal:Mean
(1+0)/2

0.5

In [28]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

**Situation-2**

In [29]:
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**Situation-3**

In [32]:
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**Situation-4**

In [ ]:
course=['DS','AI','DS','DEVOPS','AI','DEVOPS','AI']
fee=[30000,2700,30000,2200,3000,22000]

**KNNImputer**

- KNN : K-nearest neighbours
- where k is a number
- insted of taking avg of all the values data
    - first will find the neighbours who are close with missing data
    - by using euclidian distance calculation will identify the neighbours rows
    - suppose k=2 will identify two closeset rows
    - those closest row values will take it will calculate the mean
    - finally will fill with the mean

In [35]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

In [39]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=2)
pd.DataFrame(knn.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0